### PR TITLE
using ... for ... supporting functions and global

### LINKED ISSUE #674: "using ... for T global;" not supported
Solidity v0.8.13 has [extended](https://blog.soliditylang.org/2022/03/16/solidity-0.8.13-release-announcement/) the `using for` directive considerably. It is now possible to append the `global` keyboard to globally bind some functions to a user-defined value type (another feature which has been [added](https://blog.soliditylang.org/2021/09/27/user-defined-value-types) in v0.8.8).

`prettier-plugin-solidity` breaks when the new `using ... for T global` syntax is used. Here's an example:

```solidity
// SPDX-License-Identifier: Unlicense
pragma solidity >=0.8.9;

type SD59x18 is int256;
using {
    add
} for SD59x18 global;

function add(SD59x18 x, SD59x18 y) pure returns (SD59x18 result) {
    return SD59x18.wrap(SD59x18.unwrap(x) + SD59x18.unwrap(y));
}

    function e() pure returns (int256 result) {
        result = 2_718281828459045235;
    }
```

Prettier should remove the white spaces in front of the `e` function definition but it doesn't. If you comment the `using for` line though, it works.

<details>
<summary>Click to see VSCode logs</summary>
```text
["INFO" - 1:57:04 PM] Formatting file:///Users/paulrberg/workspace/projects/prb-math/contracts/Foo.sol
["INFO" - 1:57:04 PM] Using config file at '/Users/paulrberg/workspace/projects/prb-math/.prettierrc.yaml'
["INFO" - 1:57:04 PM] Using ignore file (if present) at /Users/paulrberg/workspace/projects/prb-math/.prettierignore
["INFO" - 1:57:04 PM] File Info:
{
  "ignored": false,
  "inferredParser": "solidity-parse"
}
["INFO" - 1:57:04 PM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 1:57:04 PM] Prettier Options:
{
  "filepath": "/Users/paulrberg/workspace/projects/prb-math/contracts/Foo.sol",
  "parser": "solidity-parse",
  "useTabs": false,
  "tabWidth": 4,
  "endOfLine": "auto",
  "arrowParens": "avoid",
  "bracketSpacing": true,
  "importOrder": [
    "<THIRD_PARTY_MODULES>",
    "^[./]"
  ],
  "importOrderParserPlugins": [
    "typescript"
  ],
  "importOrderSeparation": true,
  "importOrderSortSpecifiers": true,
  "printWidth": 120,
  "singleQuote": false,
  "trailingComma": "all"
}
["ERROR" - 1:57:04 PM] Error formatting document.
Error: The specified node does not exist
    at FileLevelConstantContext.getChild (/Users/paulrberg/workspace/projects/prb-math/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/src/ParserRuleContext.ts:257:10)
    at FileLevelConstantContext.getRuleContext (/Users/paulrberg/workspace/projects/prb-math/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/src/ParserRuleContext.ts:336:15)
    at FileLevelConstantContext.identifier (/Users/paulrberg/workspace/projects/prb-math/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/src/antlr/SolidityParser.ts:7435:15)
    at ASTBuilder.visitFileLevelConstant (/Users/paulrberg/workspace/projects/prb-math/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/src/ASTBuilder.ts:1277:22)
    at FileLevelConstantContext.accept (/Users/paulrberg/workspace/projects/prb-math/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/src/antlr/SolidityParser.ts:7460:19)
    at ASTBuilder.visit (/Users/paulrberg/workspace/projects/prb-math/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/src/tree/AbstractParseTreeVisitor.ts:24:15)
    at /Users/paulrberg/workspace/projects/prb-math/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/src/ASTBuilder.ts:53:59
    at Array.map (<anonymous>)
    at ASTBuilder.visitSourceUnit (/Users/paulrberg/workspace/projects/prb-math/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/src/ASTBuilder.ts:53:39)
    at SourceUnitContext.accept (/Users/paulrberg/workspace/projects/prb-math/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/src/antlr/SolidityParser.ts:6867:19)
    at ASTBuilder.visit (/Users/paulrberg/workspace/projects/prb-math/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/src/tree/AbstractParseTreeVisitor.ts:24:15)
    at Object.parse (/Users/paulrberg/workspace/projects/prb-math/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/src/parser.ts:67:14)
    at Object.parse (/Users/paulrberg/workspace/projects/prb-math/node_modules/prettier-plugin-solidity/src/parser.js:18:25)
    at Object.parse$d [as parse] (/Users/paulrberg/workspace/projects/prb-math/node_modules/prettier/index.js:12975:19)
    at coreFormat (/Users/paulrberg/workspace/projects/prb-math/node_modules/prettier/index.js:14525:16)
    at formatWithCursor$1 (/Users/paulrberg/workspace/projects/prb-math/node_modules/prettier/index.js:14765:14)
    at /Users/paulrberg/workspace/projects/prb-math/node_modules/prettier/index.js:60959:12
    at Object.Success [as format] (/Users/paulrberg/workspace/projects/prb-math/node_modules/prettier/index.js:60979:12)
    at t.default.format (/Users/paulrberg/.vscode/extensions/esbenp.prettier-vscode-9.5.0/src/PrettierEditService.ts:463:45)
    at t.PrettierEditProvider.provideEdits (/Users/paulrberg/.vscode/extensions/esbenp.prettier-vscode-9.5.0/src/PrettierEditService.ts:322:22)
    at B.provideDocumentFormattingEdits (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:102917)
["INFO" - 1:57:04 PM] Formatting completed in 0.006ms.
```
</details>

### PR DESCRIPTION
**Pull request by Janther**
Closes #674

Adding support for a list of functions for `UsingForDeclaration`s
Adding support for the word global

### CODE REVIEW

File: src/nodes/UsingForDeclaration.js [hunk 1]
```diff
@@ -1,10 +1,26 @@
...
+} = require('prettier');
+
+const printSeparatedList = require('./print-separated-list');
+
 const UsingForDeclaration = {
-  print: ({ node, path, print }) => [
+  print: ({ node, path, print, options }) => [
     'using ',
-    node.libraryName,
+    node.functions && node.functions.length
```
Comment (fvictorio) [inline src/nodes/UsingForDeclaration.js:12]: I would remove the `.length` check:

```suggestion
    node.functions
```

Even if this is not technically allowed by the grammar, I think it's more future-proof to allow a potential result of `using {} for ...`. The alternative is to use `node.libraryName`, which will be undefined and make the process fail.

Comment (Janther) [reply src/nodes/UsingForDeclaration.js:12]: `node.functions` is always an Array even if it's an empty one :(

Comment (fvictorio) [reply src/nodes/UsingForDeclaration.js:12]: Oh :man_facepalming: You are right, sorry.

**Review by fvictorio — APPROVED** [review]
