### PR TITLE
ElementaryTypeName takes care of how to print state mutability

### LINKED ISSUE #226: Removed wrong keywords when auto-formatting
The address payable keyword is wrongly corrected as address when using the helper contract Address.sol from OpenZeppelin. What I had in the smart contract was like

```using Address for address payable;```
But got wrongly auto-corrected as

```using Address for address;```

This issue was raised github.com/juanfranblanco/vscode-solidity/issues/162 by @maxweng

### PR DESCRIPTION
**Pull request by Janther**
fixes #226

Before the PR we were manually choosing where to print state mutability in `ArrayTypeName` and `VariableDeclaration`.
Now we rely on `ElementaryTypeName` to do that for us.
plus a small refactor on `VariableDeclaration`

### CODE REVIEW

File: src/nodes/VariableDeclaration.js [hunk 1]
```diff
@@ -1,38 +1,39 @@
...
+
+const visibility = node =>
+  node.visibility && node.visibility !== 'default'
+    ? concat([' ', node.visibility])
+    : '';
+
+const constantKeyword = node => (node.isDeclaredConst ? ' constant' : '');
+
+const storageLocation = node =>
+  node.storageLocation && node.visibility !== 'default'
```
Comment (Janther) [inline src/nodes/VariableDeclaration.js]: This is the only place where I think the code is a bit weird by asking whether `node.visibility !== 'default'` to make a choice for `storageLocation` but I took it from the original code.
What do you think @fvictorio @mattiaerre ??

Comment (fvictorio) [reply src/nodes/VariableDeclaration.js]: I think this makes sense, because `node.visibility === 'default'` means there's no explicit visibility in the original code.

Comment (mattiaerre) [reply src/nodes/VariableDeclaration.js]: I agree @Janther why is visibility necessary to determine the location? it looks odd to me too. But it seems to work so I'll go ahead, approve and merge
